// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmIeYZGsO-MAzNJYsaNwEVjZKnWi1fx4Y',
    appId: '1:930667353280:web:a7f35fed120a90b70b0925',
    messagingSenderId: '930667353280',
    projectId: 'authtutorial-85762',
    authDomain: 'authtutorial-85762.firebaseapp.com',
    storageBucket: 'authtutorial-85762.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJBE3jfCct0w7VS2X9W6EMjdMH5IZjm-k',
    appId: '1:930667353280:android:77d57799af247b500b0925',
    messagingSenderId: '930667353280',
    projectId: 'authtutorial-85762',
    storageBucket: 'authtutorial-85762.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSh-1x1zi6WwPldcQ7dsT5_3HP32oZK_g',
    appId: '1:930667353280:ios:78df89419f407c370b0925',
    messagingSenderId: '930667353280',
    projectId: 'authtutorial-85762',
    storageBucket: 'authtutorial-85762.appspot.com',
    iosClientId:
        '930667353280-205d0g7gsl7l1o0un3v6uncdlgfdg54r.apps.googleusercontent.com',
    iosBundleId: 'com.example.easueuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSh-1x1zi6WwPldcQ7dsT5_3HP32oZK_g',
    appId: '1:930667353280:ios:78df89419f407c370b0925',
    messagingSenderId: '930667353280',
    projectId: 'authtutorial-85762',
    storageBucket: 'authtutorial-85762.appspot.com',
    iosClientId:
        '930667353280-205d0g7gsl7l1o0un3v6uncdlgfdg54r.apps.googleusercontent.com',
    iosBundleId: 'com.example.easueuth',
  );
}
